import React, { useState, useEffect, useRef } from 'react';
import { renderMarkdown } from '../../utils/markdownRenderer';
import {
    Chart,
    LineController,
    BarController,
    LineElement,
    BarElement,
    PointElement,
    CategoryScale,
    LinearScale,
    Legend,
    Tooltip,
    Title
} from 'chart.js';
import { useExperiment } from '../../services';
import { useToast } from '../../toast';
import { runPublicationAgent, parseGeminiError } from '../../services';
import { AgenticAnalysisView } from '../common/AgenticAnalysisView';

// Register Chart.js components safely
try {
    if (Chart) {
        Chart.register(
            LineController,
            BarController,
            LineElement,
            BarElement,
            PointElement,
            CategoryScale,
            LinearScale,
            Legend,
            Tooltip,
            Title
        );
    }
} catch (e) {
    console.warn("Chart.js registration warning:", e);
}

export const FinalPublicationView = ({ publicationText, onRegenerate, showRegenerate = true }) => {
    const { addToast } = useToast();
    const { activeExperiment } = useExperiment();
    const contentRef = useRef<HTMLDivElement>(null);

    // Determine the nature of the data source for the disclaimer
    const step6Output = activeExperiment.stepData[6]?.summary || activeExperiment.stepData[6]?.output || '';
    const isManualData = step6Output.toLowerCase().includes('manually entered');

    // Construct the Disclaimer Blocks
    const disclaimerHTML = `
        <div style="background-color: #fff3cd; color: #856404; padding: 20px; border: 1px solid #ffeeba; border-radius: 8px; margin-bottom: 30px; font-family: sans-serif; line-height: 1.5;">
            <div style="font-weight: bold; margin-bottom: 8px; text-transform: uppercase; font-size: 0.9em;">
                ⚠️ AI Generation Disclaimer
            </div>
            <div style="font-size: 0.95em;">
                This research paper was generated by an Artificial Intelligence system. Consequently, it may contain errors, hallucinations, or inaccuracies.
                ${!isManualData ? '<br/><br/><strong>NOTE:</strong> No physical experiments were performed. The results presented here are derived from AI-generated data, code-based simulations, or synthetic datasets. This document is intended strictly for theoretical investigation and ideation.' : ''}
            </div>
        </div>
        <hr style="margin-bottom: 30px; border-top: 1px solid #444;" />
    `;

    const disclaimerText = `⚠️ AI GENERATION DISCLAIMER: This research paper was generated by an Artificial Intelligence system. Consequently, it may contain errors, hallucinations, or inaccuracies.\n${!isManualData ? 'NOTE: No physical experiments were performed. The results presented here are derived from AI-generated data, code-based simulations, or synthetic datasets. This document is intended strictly for theoretical investigation and ideation.\n' : ''}\n---\n\n`;

    useEffect(() => {
        const renderContent = async () => {
            if (!publicationText || !contentRef.current) return;
    
            contentRef.current.innerHTML = `<div class="text-center p-3"><div class="spinner-border spinner-border-sm"></div> Rendering document...</div>`;
    
            let processedText = publicationText;
            const chartPlaceholders = publicationText.match(/\[CHART_(\d+):([\s\S]*?)\]/g) || [];
            
            if (chartPlaceholders.length > 0) {
                const analysisJson = activeExperiment.stepData[7]?.output || '{}';
                let analysisData: any = {};
                try {
                    analysisData = JSON.parse(analysisJson.replace(/```json/g, '').replace(/```/g, ''));
                } catch(e) {
                    console.error("Failed to parse analysis JSON for charts", e);
                }
                const charts = analysisData.charts || []; 
    
                for (const placeholder of chartPlaceholders) {
                    const match = placeholder.match(/\[CHART_(\d+):([\s\S]*?)\]/);
                    if (!match) continue;
    
                    const chartIndex = parseInt(match[1], 10) - 1;
                    const caption = match[2];
    
                    if (charts[chartIndex] && charts[chartIndex].imageData) {
                        const dataUrl = `data:image/png;base64,${charts[chartIndex].imageData}`;
                        const imgTag = `<figure style="text-align: center;"><img src="${dataUrl}" alt="${caption}" style="max-width: 80%; height: auto; display: block; margin: 1rem auto; border: 1px solid #444;" /><figcaption style="font-size: 0.9em; color: #aaa; margin-top: 0.5em;">${caption}</figcaption></figure>`;
                        processedText = processedText.replace(placeholder, imgTag);
                    } else {
                         processedText = processedText.replace(placeholder, `<p class="text-warning small border border-warning p-2 rounded">[Chart placeholder found but data unavailable for Index ${chartIndex + 1}]</p>`);
                    }
                }
            }
    
            // Render Markdown and prepend the disclaimer
            if (contentRef.current) {
                const renderedBody = renderMarkdown(processedText);
                contentRef.current.innerHTML = disclaimerHTML + renderedBody;
            }
        };
    
        renderContent();
    }, [publicationText, activeExperiment, disclaimerHTML]);
    

    const handleDownload = (format: 'md' | 'doc' | 'pdf' | 'txt') => {
        const { title, id } = activeExperiment;
        if (format === 'pdf') {
            addToast("Preparing a print-friendly view...", "info");
            const printContent = contentRef.current?.innerHTML || '';
            const printWindow = window.open('', '_blank');
            if (!printWindow) {
                addToast("Could not open a new window. Please check your browser's pop-up blocker.", 'warning');
                return;
            }
            printWindow.document.write(`
                <!DOCTYPE html>
                <html>
                <head>
                    <title>Print - ${title}</title>
                    <style>
                        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 20px auto; }
                        h1, h2, h3, h4 { color: #000; }
                        pre, code { background-color: #f4f4f4; padding: 2px 4px; border-radius: 4px; font-family: monospace; }
                        pre { padding: 1em; overflow: auto; }
                        img { max-width: 100%; height: auto; }
                        figure { page-break-inside: avoid; }
                    </style>
                </head>
                <body>
                    ${printContent}
                    <script>
                        setTimeout(() => {
                            window.print();
                            window.close();
                        }, 500);
                    </script>
                </body>
                </html>
            `);
            printWindow.document.close();
            return;
        }

        let blob;
        let filename = `${title.replace(/ /g, '_')}_${id}`;
        
        if (format === 'doc') {
            // For Word, we use the HTML content with the disclaimer already injected
            const htmlContent = `
                <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
                <head><meta charset='utf-8'><title>${title}</title></head>
                <body>${contentRef.current?.innerHTML}</body>
                </html>`;
            blob = new Blob(['\ufeff', htmlContent], { type: 'application/msword' });
            filename += '.doc';
        } else {
            // For Text/Markdown, we prepend the plain text disclaimer
            const rawContent = format === 'md' ? publicationText : (contentRef.current?.innerText || publicationText);
            const contentWithDisclaimer = disclaimerText + rawContent;
            blob = new Blob([contentWithDisclaimer], { type: 'text/plain' });
            filename += `.${format}`;
        }
        
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = filename;
        link.click();
        URL.revokeObjectURL(url);
    };

    return (
        <div>
            <div className="d-flex justify-content-end mb-2">
                {showRegenerate && 
                    <button className="btn btn-sm btn-outline-secondary me-auto" onClick={onRegenerate}>
                        <i className="bi bi-arrow-clockwise me-1"></i> Regenerate with Agents
                    </button>
                }
                <div className="btn-group">
                    <button type="button" className="btn btn-sm btn-secondary dropdown-toggle" data-bs-toggle="dropdown">
                       <i className="bi bi-download me-1"></i> Download As
                    </button>
                    <ul className="dropdown-menu dropdown-menu-end">
                        <li><a className="dropdown-item" href="#" onClick={() => handleDownload('md')}>Markdown (.md)</a></li>
                        <li><a className="dropdown-item" href="#" onClick={() => handleDownload('txt')}>Plain Text (.txt)</a></li>
                        <li><a className="dropdown-item" href="#" onClick={() => handleDownload('doc')}>Word Document (.doc)</a></li>
                         <li><a className="dropdown-item" href="#" onClick={() => handleDownload('pdf')}>PDF (Print)</a></li>
                    </ul>
                </div>
            </div>
            <div ref={contentRef} className="generated-text-container" style={{ minHeight: '50vh' }}>
                {/* Content is rendered here via useEffect */}
            </div>
        </div>
    );
};

export const PublicationExporter = () => {
    const { activeExperiment, updateExperiment, isAuthenticated } = useExperiment();
    const { addToast } = useToast();
    const [agenticRun, setAgenticRun] = useState({
        status: 'idle',
        iterations: 0,
        maxIterations: 5,
        logs: [],
    });
    
    const isMounted = useRef(true);
    useEffect(() => {
        isMounted.current = true;
        return () => { isMounted.current = false; };
    }, []);

    const stepData = activeExperiment.stepData[10] || {};

    const performAgenticDraft = async () => {
        if (!isAuthenticated || agenticRun.status === 'running') return;
        setAgenticRun({ status: 'running', logs: [], iterations: 0, maxIterations: 5 });

        try {
            const finalDoc = await runPublicationAgent({
                experiment: activeExperiment,
                updateLog: (agent, message) => {
                    if (isMounted.current) {
                        setAgenticRun(prev => ({
                            ...prev,
                            logs: [...prev.logs, { agent, message }],
                            iterations: prev.iterations + 1
                        }));
                    }
                }
            });

            if (!isMounted.current) return;

            const finalStepData = { ...stepData, output: finalDoc };
            await updateExperiment({ ...activeExperiment, stepData: { ...activeExperiment.stepData, 10: finalStepData } });
            setAgenticRun(prev => ({ ...prev, status: 'success' }));
            addToast("Publication draft generated.", "success");
        } catch (error) {
             if (!isMounted.current) return;
             const errorMessage = parseGeminiError(error, "Draft generation failed.");
             addToast(errorMessage, 'danger');
             setAgenticRun(prev => ({
                ...prev,
                status: 'failed',
                logs: [...prev.logs, { agent: 'System', message: `ERROR: ${errorMessage}` }]
             }));
        }
    };

    if (stepData.output) {
        return (
            <FinalPublicationView 
                publicationText={stepData.output} 
                onRegenerate={performAgenticDraft} 
                showRegenerate={true}
            />
        );
    }

    return (
        <div className="publication-exporter-container">
            <div className="text-center p-5 border border-secondary border-opacity-10 rounded-4 bg-dark bg-opacity-10 my-3">
                    <i className="bi bi-file-earmark-text mb-3 text-primary-glow opacity-50 d-block" style={{ fontSize: '2.5rem' }}></i>
                <h5 className="fw-bold mb-2">Draft Publication</h5>
                <p className="text-white-50 small mb-4 mx-auto" style={{maxWidth: '350px'}}>
                    Synthesize all research nodes into a comprehensive scientific manuscript.
                </p>
                <button
                    className="btn btn-primary px-5 py-2 rounded-pill shadow-sm"
                    onClick={performAgenticDraft}
                    disabled={agenticRun.status === 'running'}
                >
                    {agenticRun.status === 'running' ? 'Drafting...' : 'Start Agentic Drafter'}
                </button>
            </div>
                {(agenticRun.logs.length > 0 || agenticRun.status === 'running') && (
                <div className="mt-4 border-top border-secondary border-opacity-10 pt-4">
                    <AgenticAnalysisView
                        agenticRun={agenticRun}
                        title="Publication Agent Progress"
                        subtitle="Synthesizing final manuscript from experiment data."
                    />
                </div>
            )}
        </div>
    );
};